### ISSUE TITLE
Still Maintained? How to install on 0.13+?

### ISSUE THREAD

**Issue by ghostsquad** [bwoznicki/terraform-provider-assert#1]
Is this still maintained? Terraform changed how providers are installed in 0.13+ and so I think a provider block is needed, and likely this provider should be officially published. Not sure.

Main question is whether or not you are still maintaining this?

**Comment by bwoznicki** [comment]
Hi @ghostsquad didn't get a chance to test with 0.13 yet but will check tomorrow. Officially terraform will not support this ( long story ) ...

**Comment by ghostsquad** [comment]
Officially they won't support this? What does that mean?

**Comment by bwoznicki** [comment]
hi @ghostsquad just tested with 0.13+ and updated README with instruction of how to use it.

"Officially they won't support this? What does that mean?" last time I checked they would not want it in official terraform registry, but things have changed now so might try again...

**Comment by bwoznicki** [comment]
@ghostsquad I thought you would like to know that assert is now available directly from terraform repository: https://registry.terraform.io/providers/bwoznicki/assert/latest/docs/data-sources/test

**Comment by ghostsquad** [comment]
Yaya! 🥳
